****************************************************************																																
*   THIS FILE IS GENERATED BY THE SCREEN PAINTER.              *																																
*   NEVER CHANGE IT MANUALLY, PLEASE !                         *																																
****************************************************************																																
%_DYNPRO																																
ZEQB_COCKPIT																																
9000																																
750																																
             40																																
%_HEADER																																
ZEQB_COCKPIT                            9000 9000     25118192 37  0  0 35159  0G P                              20230708122513																																
%_DESCRIPTION																																
Tela do cockpit equipe B																																
%_FIELDS																																
		CHAR	 74	00	00	00	30	00	  6	 46		  0	  0	  0		 20	R				  0	  0	101							_________________________________________________________________________		
LBTITLE	0	CHAR	 34	00	00	00	30	00	  7	 66		  0	  0	  0		  0					  0	  0								Sistema_de_controle_de_transportes		
LB1	0	CHAR	 37	00	00	00	30	00	  9	 50		  0	  0	  0		  0					  0	  0								Extrair_dados_de_funcionários________		
BTNPESQUISAR1		CHAR	 25	00	00	00	30	00	  9	 92		  0	  0	  0		 23	P				  0	  0	102							@0V@_Executar____________	                                                                                                                                                                        FFIND_A	
LB2	0	CHAR	 37	00	00	00	30	00	 11	 50		  0	  0	  0		  0					  0	  0								Importar_número_dos_cartões__________		
BTNPESQUISAR2		CHAR	 25	00	00	00	30	00	 11	 92		  0	  0	  0		 23	P				  0	  0	103							@0V@_Executar____________	                                                                                                                                                                        FFIND_B	
LB3	0	CHAR	 37	00	00	00	30	00	 13	 50		  0	  0	  0		  0					  0	  0								Importar_linhas_de_transportes_______		
BTNPESQUISAR3		CHAR	 25	00	00	00	30	00	 13	 92		  0	  0	  0		 23	P				  0	  0	104							@0V@_Executar____________	                                                                                                                                                                        FFIND_C	
LB4	0	CHAR	 37	00	00	00	30	00	 15	 50		  0	  0	  0		  0					  0	  0								Relatório_das_linhas_de_transportes__		
BTN4		CHAR	 25	00	00	00	30	00	 15	 92		  0	  0	  0		 23	P				  0	  0	105							@0V@_Executar____________	                                                                                                                                                                        FFIND_D	
LB5	0	CHAR	 37	00	00	00	30	00	 17	 50		  0	  0	  0		  0					  0	  0								Relatório_dos_cartões_de_transportes_		
BTN5		CHAR	 25	00	00	00	30	00	 17	 92		  0	  0	  0		 23	P				  0	  0	106							@0V@_Executar____________	                                                                                                                                                                        FFIND_E	
LB6	0	CHAR	 37	00	00	00	30	00	 19	 50		  0	  0	  0		  0					  0	  0								Cálculo_de_tickets_mensais___________		
BTN6		CHAR	 25	00	00	00	30	00	 19	 92		  0	  0	  0		 23	P				  0	  0	107							@0V@_Executar____________	                                                                                                                                                                        FFIND_F	
LB7	0	CHAR	 37	00	00	00	30	00	 21	 50		  0	  0	  0		  0					  0	  0								Gerar_pedido_de_compras_de_créditos__		
BTN7		CHAR	 25	00	00	00	30	00	 21	 92		  0	  0	  0		 23	P				  0	  0	108							@0V@_Executar____________	                                                                                                                                                                        FFIND_G	
LB8	0	CHAR	 37	00	00	00	30	00	 23	 50		  0	  0	  0		  0					  0	  0								Histórico_de_pedido_de_compras_______		
BTN8		CHAR	 25	00	00	00	30	00	 23	 92		  0	  0	  0		 23	P				  0	  0	109							@0V@_Executar____________	                                                                                                                                                                        FFIND_H	
		CHAR	 20	80	10	00	00	00	255	  1	O	  0	  0	  0		  0					  0	  0								____________________		
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
 MODULE STATUS_9000.																																
*																																
PROCESS AFTER INPUT.																																
 MODULE USER_COMMAND_9000.																																
%_PARAMS																																
																																
