****************************************************************																																
*   THIS FILE IS GENERATED BY THE SCREEN PAINTER.              *																																
*   NEVER CHANGE IT MANUALLY, PLEASE !                         *																																
****************************************************************																																
%_DYNPRO																																
ZEQB_COCKPIT_ESCALA																																
9001																																
750																																
             40																																
%_HEADER																																
ZEQB_COCKPIT_ESCALA                     9001 9001     26118192 37  0  0 34146  0G P                              20230712120915																																
%_DESCRIPTION																																
Tela Escala																																
%_FIELDS																																
		CHAR	 62	00	00	00	30	00	  7	 58		  0	  0	  0		 20	R				  0	  0	101							_____________________________________________________________		
TITLE	0	CHAR	 25	00	00	00	30	00	  8	 77		  0	  0	  0		  0					  0	  0								Requisição_Recarga_Cartão		
LBNAME	0	CHAR	 13	00	00	00	30	00	 10	 63		  0	  0	  0		  0					  0	  0								Codigo_Cartão		
ZEQB_CARTOES-COD_CARTAO	N	NUMC	 10	80	00	80	00	00	 10	 77		  0	  0	  0		 34					  0	  0								__________	 DL K	
LBEMISSAO	0	CHAR	  7	00	00	00	30	00	 12	 63		  0	  0	  0		  0					  0	  0								Emissão		
GWA_CARTOES-DATA_EMISSAO	D	DATS	 13	80	00	80	30	00	 12	 71		  0	  0	  0		  0					  0	  0								_____________		
LBVALID	0	CHAR	  9	00	00	00	30	00	 12	 88		  0	  0	  0		  0					  0	  0								Expira_em		
GWA_CARTOES-DATA_VALIDADE	D	DATS	 13	80	00	80	30	00	 12	 98		  0	  0	  0		  0					  0	  0								_____________		
LBCODLIN	0	CHAR	 12	00	00	00	30	00	 14	 63		  0	  0	  0		  0					  0	  0								Codigo_Linha		
LBVAL	0	CHAR	 12	00	00	00	30	00	 14	 99		  0	  0	  0		  0					  0	  0								Valor_Ticket		
ZEQB_CADLINHAS-COD_LINHA	N	NUMC	  4	80	00	80	00	00	 15	 63		  0	  0	  0		 35					  0	  0								____	 DL K	
GWA_CADLIN-VAL_UNIT	C	CHAR	 12	80	00	80	30	00	 15	 99		  0	  0	  0		  0					  0	  0								____________		
LBTICKET	0	CHAR	 21	00	00	00	30	00	 17	 63		  0	  0	  0		  0					  0	  0								Quantidade_Ticket_Dia		
LBVALTOT	0	CHAR	 11	00	00	00	30	00	 17	 88		  0	  0	  0		  0					  0	  0								Valor_Total		
QTD_TICKET	N	NUMC	 21	80	00	80	00	00	 18	 63		  0	  0	  0		  0					  0	  0								_____________________		
VAL_TOT	P	DEC	 11	80	00	80	30	00	 18	 88		  0	  0	  0		  0					  0	  0								___________		
LBMENSAL	0	CHAR	  4	00	00	00	30	00	 20	 63		  0	  0	  0		  0					  0	  0								Dias		
LBDE	0	CHAR	 11	00	00	00	30	00	 21	 63		  0	  0	  0		  0					  0	  0								Inicio_____	                                                                                                                                                                                                                                                        X	
LV_DATA_DE	D	DATS	 10	80	00	80	30	00	 21	 75		  0	  0	  0		  0					  0	  0								__________		
LBATE	0	CHAR	 11	00	00	00	30	00	 22	 63		  0	  0	  0		  0					  0	  0								Termino____	                                                                                                                                                                                                                                                        X	
LV_DATA_ATE	D	DATS	 10	80	00	80	30	00	 22	 75		  0	  0	  0		  0					  0	  0								__________		
LBQUANTIDADE	0	CHAR	 11	00	00	00	30	00	 22	 90		  0	  0	  0		  0					  0	  0								Quantidade:		
QTD_DIAS	N	NUMC	  9	80	00	80	30	00	 22	103		  0	  0	  0		  0					  0	  0								_________		
BTNDIAS		CHAR	  9	00	00	00	30	00	 24	 63		  0	  0	  0		  0	P				  0	  0	102							Simular__	                                                                                                                                                                        FSIMULAR	
BTNGERAR		CHAR	 11	00	00	00	30	00	 24	102		  0	  0	  0		  9	P				  0	  0	103							@EQ@_Gerar_	                                                                                                                                                                        FGRAVA	
		CHAR	 20	80	10	00	00	00	255	  1	O	  0	  0	  0		  0					  0	  0								____________________		
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
  MODULE STATUS_9001.																																
  MODULE HABILITA_CAMPOS.																																
																																
PROCESS AFTER INPUT.																																
  MODULE USER_COMMAND_9001.																																
%_PARAMS																																
																																
