  method SAVE_LINHAS.
     DATA: GT_ZEQB_CADLINHAS TYPE TABLE OF ZEQB_CADLINHAS,
        GWA_ZDEQB_CADLINHAS  TYPE ZEQB_CADLINHAS.

  SELECT SINGLE COD_LINHA INTO @GWA_ZDEQB_CADLINHAS
     FROM ZEQB_CADLINHAS
    WHERE COD_LINHA EQ @IN_COD_LINHA.

  IF SY-SUBRC NE 0.

   GWA_ZDEQB_CADLINHAS-COD_LINHA = IN_COD_LINHA.
   GWA_ZDEQB_CADLINHAS-NOME_LINHA = IN_NOME_LINHA.
   GWA_ZDEQB_CADLINHAS-VAL_UNIT = IN_VAL_UNIT.
   GWA_ZDEQB_CADLINHAS-WAERS = WAERS.

    MODIFY ZEQB_CADLINHAS FROM GWA_ZDEQB_CADLINHAS.
    COMMIT WORK.

    OUT_MSG = 1.

  ELSE.

    OUT_MSG = 0.

  ENDIF.
  endmethod.
