  method SAVE_CARD.

  DATA: GT_SAVE_IN  TYPE TABLE OF ZEQB_CARTOES,
        GWA_SAVE_IN TYPE ZEQB_CARTOES.

  SELECT SINGLE COD_CARTAO INTO @GWA_SAVE_IN
     FROM ZEQB_CARTOES
    WHERE COD_CARTAO EQ @IN_COD_CARTAO.

  IF SY-SUBRC NE 0.

    GWA_SAVE_IN-COD_CARTAO = IN_COD_CARTAO.
    GWA_SAVE_IN-CPF = IN_CPF.
*    GWA_SAVE_IN-NAME = IN_NAME.
    GWA_SAVE_IN-DATA_EMISSAO = IN_DATA_EMISSAO.
    GWA_SAVE_IN-DATA_VALIDADE = IN_DATA_VALIDADE.
    MODIFY ZEQB_CARTOES FROM GWA_SAVE_IN.
    COMMIT WORK.

    OUT_MSG = 1.

  ELSE.

    OUT_MSG = 0.
    endif.

 endmethod.
